# ===================================
# Aetheris Block Material Mapping
# ===================================


# Stone

block.1=stone granite polished_granite diorite andesite


# Wood

block.2=oak_planks spruce_planks birch_planks jungle_planks acacia_planks dark_oak_planks


# Ice

block.3=ice packed_ice blue_ice


# Snow

block.4=snow snow_block


# Glass

block.5=glass white_stained_glass blue_stained_glass

