# ===================================
# Aetheris Shader
# Minecraft Architectural Rendering
# ===================================

name=Aetheris Shader v0.1 Beta


clouds=off
oldLighting=false


# Pipeline

composite.enabled=true


# Shadow

shadowMapResolution=2048
shadowDistance=160


# GBuffer

DRAWBUFFERS:012