# ===================================
# Aetheris Shader
# ===================================


name=Aetheris Shader



clouds = off

oldLighting = false



# ===================================
# Buffers
# ===================================


DRAWBUFFERS:0123



# ===================================
# Shadow
# ===================================


shadowMapResolution=2048

shadowDistance=160



# ===================================
# Composite
# ===================================


composite.enabled=true